### ISSUE TITLE
Syntax highlighting no longer working with `ipython==8.7.0`

### ISSUE THREAD

**Issue by nvaytet** [spatialaudio/nbsphinx#687] opened 2022-12-05 09:51 UTC
I do not know if the issue lies with `nbsphinx` or `nbconvert`, but after upgrading from `ipython==8.5.0` to `ipython==8.7.0`, the syntax highlighting in our sphinx docs is gone.
Only black text in the code blocks.

Before:
![Screenshot at 2022-12-05 10-48-18](https://user-images.githubusercontent.com/39047984/205606919-7dda2d7d-084e-4247-bfc8-c4dc11d6cd08.png)

After:
![Screenshot at 2022-12-05 10-51-21](https://user-images.githubusercontent.com/39047984/205606938-1ce5f952-a93d-4d33-b7bd-b8e9f3c46e64.png)

**Comment by maparent** [comment] 2022-12-06 03:49
I can confirm that the `pygments.lexers` entry is no longer added to entry_points.txt. 
It is because of the explicit
```python
setup_args["entry_points"] = {"console_scripts": find_entry_points()}```
at line 142 of setup.py, which should also include the `pygments.lexers` entry present in `setup.cfg`

**Comment by mgeier** [comment] 2022-12-06 12:46
Thanks @nvaytet for reporting this and @maparent for finding the root cause for the problem.

It looks like the IPython folks are already working on fixing this: https://github.com/ipython/ipython/issues/13845, https://github.com/ipython/ipython/pull/13848.

In the meantime, a possible work-around should be to disallow the broken IPython version:

    ipython!=8.7.0

**Comment by al-jshen** [comment] 2022-12-09 16:26
Had the same issue here. The old workaround of adding `"IPython.sphinxext.ipython_console_highlighting"` to `"extensions"` in `conf.py` from https://github.com/spatialaudio/nbsphinx/issues/24 seems to fix the problem for me.

**Comment by mgeier** [comment] 2022-12-21 20:08
A little update: https://github.com/ipython/ipython/pull/13848 has been merged, now we are only waiting for a new release.

**Comment by Zethson** [comment] 2023-01-04 19:49
8.8.0 just got released yesterday

**Closed** 2023-01-17 19:47 UTC
