### ISSUE TITLE
Commit "Rewrite local links for RST" emits "WARNING: file not found"

### ISSUE THREAD

**Issue by jschueller** [spatialaudio/nbsphinx#174] opened 2018-03-29 15:55 UTC
Latest release 0.3.2 breaks the world for us as the last commit https://github.com/spatialaudio/nbsphinx/commit/7e791655205beebccce65b920d4cf798c8f6d614 breaks a link to a plot directive script (here empirical_cdf-1.py):

```
Warning, treated as error
/tmp/openturns/python/src/sphinx_build/theory/data_analysis/empirical_cdf.rst.rst:file not found: 'theory/data_analysis/empirical_cdf-1.py'
```

Here is the rst file, it contains a plot directive and as well a link to a notebook:
https://github.com/openturns/openturns/blob/master/python/doc/theory/data_analysis/empirical_cdf.rst

Here is the rendered version, before the 0.3.2 update:
http://openturns.github.io/openturns/master/theory/data_analysis/empirical_cdf.html

**Comment by mgeier** [comment] 2018-03-30 07:40
So you are saying everything works perfectly but there is a warning?

**Comment by jschueller** [comment] 2018-03-30 08:08
No, the renderend version was built with 0.3.1, before the 0.3.2 update. We treat sphinx warnings as errors. If I believe the message emited, the pyplot script may be missing in the html.

**Comment by mgeier** [comment] 2018-03-30 09:32
And what happens if you allow warnings?

**Comment by jschueller** [comment] 2018-04-05 10:03
If I allow warnings, the build succeeds.
The problem is that it emits a huge number of these, and that prevents us from catching the other useful warnings.

I prepared a very small example with the use of nbsphinx with a plot directive: https://github.com/jschueller/foo, see the travis log at: https://travis-ci.org/jschueller/foo.

We see that it emits 4 warnings on a single plot directive. We have lots of these...

**Comment by jschueller** [comment] 2018-04-05 10:07
Note that after some checking the link to the script is not broken as I suggested, issue title changed.

**Comment by mgeier** [comment] 2018-04-05 19:16
Thanks for confirming that the warning is the only problem, now we can try to solve this.

Ideas:

* just remove the warning
* create a new config option to disable this specific warning
* modify all warnings to be able to use `supress_warnings`, already discussed in #130 

Any more ideas?

Any comments?

**Comment by jschueller** [comment] 2018-04-06 06:38
I'd prefer to actually fix the warning in nbsphinx. Do you have a rough idea of what could cause it in that commit I pointed out ?

**Comment by mgeier** [comment] 2018-04-08 09:50
I know exactly what causes it:

https://github.com/spatialaudio/nbsphinx/blob/89cbb765a1daa5aefd07f7f2f32c04da23aefc3a/src/nbsphinx.py#L1080-L1083

`nbsphinx` was already doing this for a long time for Jupyter notebooks, but with the commit you mentioned, it started to apply the same thing to *all* Sphinx source files, including RST files.

Now the problem is that the "plot" directive is generating "invalid" RST code in the sense that it uses link locations that don't exist in the *source* directory (but they will at some point exist in the *output* directory).

**Comment by jschueller** [comment] 2018-04-09 07:55
- Why do we have to touch links other than ipynbs ?
- The plot directive does not yield warnings by itself if it links to the not preexisting python script, how is this case handled ?

**Comment by mgeier** [comment] 2018-04-11 10:15
> Why do we have to touch links other than ipynbs ?

We don't have to, that's a free decision.
I thought it would be nice if links in RST files work the same as links in notebook files.
As an added benefit, those links work also when viewing the RST file on Github and other rendered RST views.
See http://nbsphinx.readthedocs.io/en/0.3.2/a-normal-rst-file.html#links-to-notebooks-and-other-sphinx-source-files

> The plot directive does not yield warnings by itself if it links to the not preexisting python script, how is this case handled ?

I don't exactly understand the question, but I'm trying to answer what I think you are asking:
Normally, the RST parser doesn't check if links point to anything meaningful, they are just blindly generated.
I added a warning message in `nbsphinx` if a link points to a non-existing local file, because if you manually write this link in a Jupyter notebook, this is most likely a mistake, e.g. a typo.
As it turns out, when extending this to RST files, there are some cases where people would either manually or via a Sphinx extension create local links that don't point to any file in the *source* directory, but to a file in the *output* directory, which is created long after parsing the source file.

**Comment by jschueller** [comment] 2018-04-11 13:32
This is clearer now.
Would it be possible to add an option to decide whether links should be checked against non-existing local files then ?

**Comment by mgeier** [comment] 2018-04-11 15:05
> Would it be possible to add an option to decide whether links should be checked against non-existing local files then ?

Sure. But what should it do for *existing* local files?
If a local link points to a non-existent file, `nbsphinx` doesn't *do* anything anyway. It's just showing the warning we're talking about.

> I found #130 is related.

It indeed is. That's why I mentioned it in https://github.com/spatialaudio/nbsphinx/issues/174#issuecomment-377488389 and https://github.com/spatialaudio/nbsphinx/issues/174#issuecomment-379046962. In fact, this issue is a duplicate of #130.

**Comment by jschueller** [comment] 2018-04-11 15:27
When the link points to a non-existent file, it could avoid emitting warnings to sphinx,
but I dont see where in the nbsphinx code this warning is explicitely raised.

**Comment by mgeier** [comment] 2018-04-11 18:45
The warning is raised in the code snippet I showed above: https://github.com/spatialaudio/nbsphinx/issues/174#issuecomment-379536943.

You could also search for this combination of words: "file not found". It should be the only match in `nbsphinx.py`.

**Comment by mgeier** [comment] 2018-04-17 10:11
@jschueller Thanks for #177!

I've just created an alternative PR: #178.
What do you think about it?

I think my PR #178 would solve your immediate problem.
But if we want to completely solve #130, we could merge your PR #177, too.

**Comment by mgeier** [comment] 2018-04-17 10:33
@jschueller Thanks for #177!

I've just created an alternative PR: #178.
What do you think about it?

I think my PR #178 would solve your immediate problem.
But if we want to completely solve #130, we could merge your PR #177, too.

**Comment by jschueller** [comment] 2018-04-17 13:00
#178 is totally ok for me, imho no need for #177

**Closed** 2018-04-18 09:14 UTC
Labels: duplicate
