### ISSUE TITLE
How to deal with non-existing kernels on ReadTheDocs?

### ISSUE THREAD

**Issue by michaelaye** [spatialaudio/nbsphinx#121] opened 2017-09-06 16:55 UTC
Hi!
I'm trying to use nbsphinx on RTD to include notebooks in my docs. 
But during the build process, things fail because my local kernel names that I use for executing the notebooks of course do not exist on RTD:

```bash
Notebook error:
NoSuchKernel in examples.ipynb:
No such kernel named conda-env-stable-py
```
How do I deal with this correctly?
Thanks!

**Comment by mgeier** [comment] 2017-09-06 20:49
Duplicate of #90?

Does `nbsphinx_kernel_name` help?

**Comment by michaelaye** [comment] 2017-09-06 20:51
I searched for that in the docs, is it undocumented?

**Comment by mgeier** [comment] 2017-09-07 06:00
Well, that depends on how you define "undocumented".
It is mentioned in [doc/conf.py](../blob/master/doc/conf.py) (which I consider part of the documentation), but the "search" function of the HTML docs won't find this.

That's where you come in!
Please feel free to add this information to the documentation and make a pull request!

**Closed** 2020-05-11 18:42 UTC

**Comment by ahuang11** [comment] 2021-02-01 02:21
For those encountering this issue and tried setting `nbsphinx_kernel_name = python3`, I realized that i needed to add `ipykernel` to `docs/requirements.txt` to make RTD find the kernel

**Comment by mgeier** [comment] 2021-02-01 09:53
Thanks @ahuang11! This is documented at https://nbsphinx.readthedocs.io/en/0.8.1/installation.html#Jupyter-Kernel and both the `requirements.txt` and `environment.yml` examples at https://nbsphinx.readthedocs.io/en/0.8.1/usage.html#Automatic-Creation-of-HTML-and-PDF-output-on-readthedocs.org contain `ipykernel`.

If you have an idea how to improve the documentation, please make a PR!

**Comment by ahuang11** [comment] 2021-02-01 14:38
Oops I didn't take a deep look, I was searching for keywords on Google and
that part of the docs never appeared. I wonder if copying the full error in
the docs would help.

**Comment by mgeier** [comment] 2021-02-01 15:22
Yes, including the error message might help people. Do you want to make a PR?

If there are more potential pitfalls like this, we might even want to make a whole new "troubleshooting" page?
