### ISSUE TITLE
Toc and autorun of cells 

### ISSUE THREAD

**Issue by rddaz2013** [spatialaudio/nbsphinx#163] opened 2018-01-21 10:49 UTC
#152 #100 #87
> With nbsphinx your notebooks just become Sphinx source files

with regard to the table of contents i am not sure about the 'just'. 

I have tried to create dynamic headings via 'Markdown (' # ... ') but sphinx does not use the headings (as Output!) For the TOC.

At the moment I am also having trouble updating cell outputs when nbsphinx is running - only the backed up cells from the last jupyterlab run will be translated.

Is the autorun option already running?

**Comment by mgeier** [comment] 2018-01-22 14:35
Regarding your first problem, you've already found the relevant issue #152. The problem is discussed there, but there wasn't any further development. Feel free to continue there.

Regarding your second problem, I don't really understand what you are saying. Can you please give a few more details?
BTW, the documentation describes under which circumstances notebooks are executed: http://nbsphinx.readthedocs.io/en/latest/executing-notebooks.html.

> Is the autorun option already running?

I'm not quite sure what you mean by "autorun option", but if it's that notebooks without outputs are executed, then yes. This was implemented since day 1.

**Comment by rddaz2013** [comment] 2018-01-24 19:25
nbsphinx is running the cells only...but the output is not written back into the jupyter notebook.

**Comment by mgeier** [comment] 2018-01-25 10:35
Yes, that's right. Notebooks are source files, which are not supposed to be changed. They might as well be read-only.
One could write the executed notebooks to disk (which is done in the `save-notebooks` branch if you are interested), but I don't think that's a good idea.

You can execute your notebook (and store the results) with

    nbconvert --to ipynb --execute my-notebook.ipynb

**Comment by rddaz2013** [comment] 2018-01-25 11:49
With the help from https://github.com/choldgraf/nbclean i can live with that. That is fine.

I can modify notebooks from other notebooks and can rewrite them. My latex template is almost ready - there a only minor changes in nbsphinx to do. I will make a new branch if i am ready - https://github.com/rddaz2013/nbsphinx

**Comment by mgeier** [comment] 2018-03-10 10:06
@rddaz2013 I'm looking forward to new pull requests!

Can I close this issue?

**Comment by rddaz2013** [comment] 2018-03-10 11:46
Yes you can

**Closed** 2018-03-10 12:26 UTC
