### ISSUE TITLE
Undefined variable in _generate_output_format

### ISSUE THREAD

**Issue by stsievert** [spatialaudio/nbsphinx#57] opened 2016-07-24 15:15 UTC
I ran into an issue where `latex_datatype` wasn't defined in `_generate_output_type` when running a nbsphinx on a precomputed notebook.

This code appears to be untested; all code should be tested.

**Comment by mgeier** [comment] 2016-07-24 15:44
Duplicate of #50?

Did you try the master branch?
This should be fixed with #51, which isn't in an official release yet.

> This code appears to be untested; all code should be tested.

#51 also adds a section for this in the example notebooks, there are no tests other than that.

If you have an idea how to implement proper tests, I'd love to see a PR for that!

**Comment by stsievert** [comment] 2016-07-24 15:47
Yes, duplicate.

Proper tests should test each function. Given specific inputs, the function
should produce specific outputs. Frameworks such as py.test and nose tests
are good for defining tests; any function named test_* is run.

On July 24, 2016 at 10:44:25 AM, Matthias Geier (notifications@github.com)
wrote:

Duplicate of #50 <https://github.com/spatialaudio/nbsphinx/issues/50>?

Did you try the master branch?
This should be fixed with #51
<https://github.com/spatialaudio/nbsphinx/pull/51>, which isn't in an
official release yet.

This code appears to be untested; all code should be tested.

#51 <https://github.com/spatialaudio/nbsphinx/pull/51> also adds a section
for this in the example notebooks, there are no tests other than that.

If you have an idea how to implement proper tests, I'd love to see a PR for
that!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/spatialaudio/nbsphinx/issues/57#issuecomment-234784284>,
or mute the thread

**Comment by mgeier** [comment] 2016-07-26 19:29
I know what tests are, but I didn't have the time or energy to implement proper automated tests yet and won't have in the foreseeable future. I'd be happy to get a PR, though.

In the meantime, the notebooks in the documentation serve as non-automated tests and they should cover most of the features. If there is something missing, again, I'm looking forward to PRs!

**Comment by mgeier** [comment] 2016-07-26 19:46
I just made a new release (0.2.9), does it solve the issue?

**Closed** 2016-09-23 15:19 UTC
Labels: bug, duplicate
