### ISSUE TITLE
Plotly graphs not showing in documentation

### ISSUE THREAD

**Issue by bluprince13** [spatialaudio/nbsphinx#128] opened 2017-10-02 23:11 UTC
Graphs generated using plotly are not showing in the documentation. Matplotlib plots show up just fine.

**Comment by mgeier** [comment] 2017-10-07 03:32
Thanks for the report!

Can you please provide an example notebook that shows the issue?

**Comment by bluprince13** [comment] 2017-10-15 20:13
https://gist.github.com/bluprince13/1a53aabe99b5a4a1ec2007a90889115b

**Comment by mgeier** [comment] 2017-10-17 11:09
OK, thanks for the example.

Just for the record, it seems to work on nbviewer: http://nbviewer.jupyter.org/gist/bluprince13/1a53aabe99b5a4a1ec2007a90889115b

Does it work with `nbconvert`?

I don't know how this is supposed to work.
Your example has two output cells. The first one has two alternative contents of the type `text/vnd.plotly.v1+html` and `text/html`, respectively. The second output cell also has two alternative contents with the same two types.
`nbsphinx` includes the `text/html` part in both cases, because it doesn't know the other type.

When loading the Sphinx-generated HTML page, I get those errors in the JS Console:

```
ReferenceError: define is not defined
ReferenceError: require is not defined
```

**Comment by bluprince13** [comment] 2017-10-18 18:23
I asked a [question](https://stackoverflow.com/questions/46269345/embed-plotly-graph-in-a-sphinx-doc) on stackoverflow on this as well. No responses yet.

**Comment by bluprince13** [comment] 2017-10-18 18:28
I can confirm that this does work with nbconvert 5.3.1. So, why is the Sphinx generated documentation not showing it ...

**Comment by mgeier** [comment] 2017-10-21 07:44
Yes, I checked.

No, I don't think that's possible.

**Comment by Juanlu001** [comment] 2017-11-15 10:04
I have tried this workaround, but still I get the `ReferenceError: requirejs is not defined`.

Code: https://github.com/poliastro/poliastro/compare/master...Juanlu001:master
Build: https://readthedocs.org/projects/juanlu-poliastro/builds/6272017/
Result: http://juanlu-poliastro.readthedocs.io/en/latest/examples/Plotting%20in%203D.html

I suspect this is because the scripts are loaded at the bottom of the page, after `require.js` is requested by the plotly graphs.

**Comment by Juanlu001** [comment] 2017-11-16 14:17
I see you're tracking this here https://github.com/rtfd/sphinx_rtd_theme/issues/328

**Comment by mgeier** [comment] 2017-11-17 10:27
Did you try it with a different HTML theme?

**Comment by Juanlu001** [comment] 2017-11-17 14:07
I can confirm locally that using a different theme fixes the problem, so this is not a nbsphinx issue.

**Comment by mgeier** [comment] 2017-11-18 11:48
@Juanlu001 OK, thanks! Did you try if https://github.com/rtfd/sphinx_rtd_theme/pull/467 fixes the problem?

**Comment by Juanlu001** [comment] 2017-11-18 19:06
Yes it does! :grin: see https://github.com/rtfd/sphinx_rtd_theme/pull/467#issuecomment-345463571

**Comment by Juanlu001** [comment] 2018-06-28 14:56
https://github.com/rtfd/sphinx_rtd_theme/pull/467 was closed because it was too complex, but now the issue is being tackled at https://github.com/rtfd/sphinx_rtd_theme/pull/545.

**Comment by Juanlu001** [comment] 2018-09-23 12:57
Some more info in https://github.com/rtfd/readthedocs.org/issues/4367#issuecomment-423814712

**Comment by mgeier** [comment] 2018-12-11 11:33
https://github.com/rtfd/sphinx_rtd_theme/pull/545 has finally be merged into the `master` branch, now we only have to wait for a new release ...

**Comment by manycoding** [comment] 2019-05-02 17:00
@mgeier I would opt for adding `require.js` here by default.
I have been tackling this issue (which now seems obvious) for some time, mostly because there are a lot of things involved and you don't know where is the problem - jupyter, plotly, sphinx, nbsphinx, rtd, your code :)

**Comment by mgeier** [comment] 2019-05-03 08:37
@manycoding I guess if `nbconvert` and `nbviewer` include `require.js`, it makes sense to have it in `nbsphinx`, too.

Would you like to make a PR?

**Closed** 2019-06-25 15:12 UTC
Labels: waiting-for-3rd-party, work-around-available

**Comment by miohtama** [comment] 2022-06-17 09:59
We had this issue for both `sphinx_rtd_theme` and `furo` theme. Because how Plotly and Sphinx themes using `require.js`, the default generated HTML output does not work within Sphinx context. You get various loading errors with require.js or other files. 

Here is our solution:

* Make sure your JavaScript loads at `<head>` in your theme. If it loads at the end of the `<body>` no workaround is going t work.
* Server `require.js` locally from Sphinx `_static` folder
* Configure `require` by using custom.js

Example `conf.py`:

```python
html_js_files = [
    "require.min.js",  # Add to your _static
    "custom.js",
]

```

Example custom.js:

```javascript
requirejs.config({
    paths: {
        base: '/static/base',
        plotly: 'https://cdn.plot.ly/plotly-2.12.1.min.js?noext',
    },
});
```

This way

* Notebook correctly renders interactive diagrams when running in Jupyter
* Notebook correctly renders interactive diagrams when viewed as static HTML files
* Notebook correctly renders interactive diagrams when viewed on ReadTheDocs

[See the example open-source documentation here](https://web3-ethereum-defi.readthedocs.io/) and [the example notebook](https://web3-ethereum-defi.readthedocs.io/tutorials/uniswap-v3-price-analysis.html).
